//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Region &quot;{0} is invalid. Please try again..
        /// </summary>
        internal static string AreaRegionsDialog_InvalidOption {
            get {
                return ResourceManager.GetString("AreaRegionsDialog_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Area Region:.
        /// </summary>
        internal static string AreaRegionsDialog_Prompt {
            get {
                return ResourceManager.GetString("AreaRegionsDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Regions.
        /// </summary>
        internal static string AreaRegionsDialog_Select {
            get {
                return ResourceManager.GetString("AreaRegionsDialog_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select an Item.
        /// </summary>
        internal static string PagedCarouselDialog_DefaultPrompt {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_DefaultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want more options?.
        /// </summary>
        internal static string PagedCarouselDialog_MoreOptions {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Please!.
        /// </summary>
        internal static string PagedCarouselDialog_ShowMe {
            get {
                return ResourceManager.GetString("PagedCarouselDialog_ShowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper to choose the right Solution area for Specialist Finder.
        /// </summary>
        internal static string RootDialog_SF_Solution_Area {
            get {
                return ResourceManager.GetString("RootDialog_SF_Solution_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong after too many invalid attemps. Maybe you can start over again..
        /// </summary>
        internal static string RootDialog_TooManyAttempts {
            get {
                return ResourceManager.GetString("RootDialog_TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ISS Bot helper.
        /// </summary>
        internal static string RootDialog_Welcome_Message {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialist Finder Request Form.
        /// </summary>
        internal static string RootDialog_Welcome_SFRequest {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_SFRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Solution Area helper.
        /// </summary>
        internal static string RootDialog_Welcome_Solution_Helper {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Solution_Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the options that you are looking for!.
        /// </summary>
        internal static string RootDialog_Welcome_Subtitle {
            get {
                return ResourceManager.GetString("RootDialog_Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Subsidiary &quot;{0} is invalid. Please try again..
        /// </summary>
        internal static string SubsidiariesDialog_InvalidOption {
            get {
                return ResourceManager.GetString("SubsidiariesDialog_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Subsidiary:.
        /// </summary>
        internal static string SubsidiariesDialog_Prompt {
            get {
                return ResourceManager.GetString("SubsidiariesDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Subsidiaries.
        /// </summary>
        internal static string SubsidiariesDialog_Select {
            get {
                return ResourceManager.GetString("SubsidiariesDialog_Select", resourceCulture);
            }
        }
    }
}
